#ifndef SWFPM_PORT_STATUS_H
#define SWFPM_PORT_STATUS_H

typedef enum {
    PORT_OK,
    PORT_STATUS_TIMEOUT,
    PORT_STATUS_UNAVAILABLE,
    PORT_STATUS_INVALID_PARAM,
    PORT_STATUS_HARDWARE_ERROR,
    PORT_STATUS_BUSY,
} PortStatus;

#endif
