#ifndef SWFPM_DOMAIN_DELIVERY_TYPES_H
#define SWFPM_DOMAIN_DELIVERY_TYPES_H


#include <stdint.h>


typedef enum {
    DELIVERY_ACKNOWLEDGED,
    DELIVERY_REJECTED_BY_SERVER,
    DELIVERY_TRANSPORT_FAILED,
    DELIVERY_TIMEOUT,
    DELIVERY_OUTCOME_UNKNOWN,
    DELIVERY_CANCELLED
} DeliveryOutcome;


typedef enum {
    TELEREC_BUILT,
    TELEREC_QUEUED,
    TELEREC_IN_FLIGHT,
    TELEREC_ACKNOWLEDGED,
    TELEREC_DROPPED
} TelemetryRecordState;

#endif /* SWFPM_DOMAIN_DELIVERY_TYPES_H */
